model_1:
  name: 'xgb_Classifier'
  params:
    learning_rate: [0.1, 0.2]
    gamma : [0.5, 0.6]
    reg_alpha : [0.1, 0.6]
    reg_lambda : [1, 2]
    max_depth : [7,8]
    subsample : [0.7, 0.8]
    scale_pos_weight : [1, 2]
    colsample_bytree : [0.5, 0.4]
model_2:
  name: 'SGDClassifier'
  params:
    alpha: [0.01, 0.03]
    max_iter: [10, 9]
    penalty : ['l2', 'l1']
    loss : ['modified_huber']
model_3:
  name: 'RandomForestClassifier'
  params:
    n_estimators: [200, 300]
    criterion: ['gini', 'entropy']
    max_depth: [15, 10]
    random_state: [0, 0]
    max_leaf_nodes: [50, 40]
